/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['AppController_health'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/widgets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List widgets for current organization */
    get: operations['WidgetsController_findAll'];
    put?: never;
    /** Create a widget */
    post: operations['WidgetsController_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/widgets/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a widget by id */
    get: operations['WidgetsController_findOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    GenericErrorDto: {
      /** @example 404 */
      statusCode: number;
      /** @example Resource not found */
      message: string;
      /** @example Not Found */
      error: string;
    };
    CreateWidgetDto: {
      /** @example My first widget */
      name: string;
      /** @example Optional description */
      description?: string;
    };
    HateoasLinkDto: {
      /** @example /v1/widgets/123e4567-e89b-12d3-a456-426614174000 */
      href: string;
      /** @example PUT */
      method?: string;
    };
    WidgetLinksDto: {
      self: components['schemas']['HateoasLinkDto'];
      collection: components['schemas']['HateoasLinkDto'];
    };
    WidgetResponseDto: {
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      id: string;
      /** @example My first widget */
      name: string;
      /** @example Optional description */
      description: Record<string, never> | null;
      /** @example 2026-09-27T12:00:00.000Z */
      createdAt: string;
      /** @example 2026-09-27T12:00:00.000Z */
      updatedAt: string;
      _links: components['schemas']['WidgetLinksDto'];
    };
    FieldValidationErrorDto: {
      /** @example name */
      field: string;
      /** @example name should not be empty */
      message: string;
    };
    ValidationErrorDto: {
      /** @example 400 */
      statusCode: number;
      /** @example Validation failed. */
      message: string;
      /** @example Bad Request */
      error: string;
      errors: components['schemas']['FieldValidationErrorDto'][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AppController_health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WidgetsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WidgetResponseDto'][];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenericErrorDto'];
        };
      };
    };
  };
  WidgetsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWidgetDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WidgetResponseDto'];
        };
      };
      /** @description Validation failed */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ValidationErrorDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenericErrorDto'];
        };
      };
    };
  };
  WidgetsController_findOne: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WidgetResponseDto'];
        };
      };
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenericErrorDto'];
        };
      };
      /** @description Widget not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GenericErrorDto'];
        };
      };
    };
  };
}
